export default {
    SELECT_TOPIC: 'SELECT_TOPIC',
    INVALIDATE_TOPIC: 'INVALIDATE_TOPIC',
    REQUEST_TWEETS: 'REQUEST_TWEETS',
    REQUEST_TWEETS_SUCCESS: 'REQUEST_TWEETS_SUCCESS',
    REQUEST_TWEETS_ERROR: 'REQUEST_TWEETS_ERROR'
}